[package]
name = "openapi-rust-runtime"
version = "0.1.0"
authors = ["Dave Syer <dsyer@vmware.com>"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
