[package]
name = "openapi-rust"
version = "0.1.0"
authors = ["Dave Syer <dsyer@vmware.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
openapi = { path = "./openapi" }

serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

[profile.release]
opt-level = "s"
