/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.19.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ImageSpec : ImageSpec defines the desired state of Image



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ImageSpec {
    /// A registry image path, e.g. \"nginx\" or \"gcr.io/my-project/app\"
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// The interval at which to check for repository updates, e.g. \"30s\" or \"1m30s\".
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
}

impl V1ImageSpec {
    /// ImageSpec defines the desired state of Image
    pub fn new() -> V1ImageSpec {
        V1ImageSpec {
            image: None,
            interval: None,
        }
    }
}


