/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.19.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ImageList : ImageList is a list of Image



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ImageList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// List of images. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    #[serde(rename = "items")]
    pub items: Vec<crate::models::V1Image>,
    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<k8s_openapi::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl V1ImageList {
    /// ImageList is a list of Image
    pub fn new(items: Vec<crate::models::V1Image>) -> V1ImageList {
        V1ImageList {
            api_version: None,
            items,
            kind: None,
            metadata: None,
        }
    }
}


