/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.19.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ImageStatus : ImageStatus defines the observed state of Image



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ImageStatus {
    #[serde(rename = "complete", skip_serializing_if = "Option::is_none")]
    pub complete: Option<bool>,
    #[serde(rename = "latestImage", skip_serializing_if = "Option::is_none")]
    pub latest_image: Option<String>,
    #[serde(rename = "observedGeneration", skip_serializing_if = "Option::is_none")]
    pub observed_generation: Option<i64>,
}

impl V1ImageStatus {
    /// ImageStatus defines the observed state of Image
    pub fn new() -> V1ImageStatus {
        V1ImageStatus {
            complete: None,
            latest_image: None,
            observed_generation: None,
        }
    }
}


